### ISSUE TITLE
Offer formatting options when pasting

### ISSUE THREAD

**Issue by afuna** [afuna/copy-link-text#3]
We can offer an options page with some kind of formatting options:
- copy link text (enabled by default; everything else is disabled)
- <a href="http://....">link text</a>
- wiki markup (look up formats)
- custom with variables:
  %%url%%
  %%text%%
  %%link-title%%
  %%page-title%%

Any others that are commonly used?

**Comment by jollychang** [comment]
enough, great!
I only use 2 formats:
 Plain Text(title-url) and html code(title-url)
